# Limpeza de Dados - Exercícios

Resolva os exercícios propostos abaixo. Os exercícios usam um dataset de reclamações registradas por cidadãos. O detaset foi derivado de dados do [Portal de Dados Abertos da Prefeitura de Curitiba](https://www.curitiba.pr.gov.br/DADOSABERTOS/).

## Leitura e análise inicial dos dados

Inicie um DataFrame a partir do arquivo `2017-02-01_156_-_Base_de_Dados_sample.csv`. Exiba algumas linhas e informações sobre os tipos identificados automaticamente pelo Pandas.

**Dica:** Caso o arquivo não seja separado por vírgulas, o Pandas não conseguirá reconhecer os campos adequadamente. Você precisará fornecer o parâmetro `sep=';'` para indicar o separador correto (neste caso, o `;`).

**Dica:** Aplicativos modernos tendem a armazenar arquivos no formato UTF-8, mas é comum encontrar arquivos codificados em outros formatos. Caso você tenha problemas para ler o arquivo, utilize o parâmetro `encoding='latin-1'` para selecionar o encoding correto (*latin-1* neste exemplo).

In [134]:
# Resposta:
import pandas as pd

# lê o arquivo CSV
df = pd.read_csv('../data/2017-02-01_156_-_Base_de_Dados_sample.csv', encoding="latin-1", sep=";")

Visualize algumas linhas de dados:

In [135]:
# Resposta:
df.head(10)

,SOLICITACAO,TIPO,ORGAO,DATA,HORARIO,ASSUNTO,SUBDIVISAO,DESCRICAO,LOGRADOURO_ASS,BAIRRO_ASS,REGIONAL_ASS,MEIO_RESPOSTA,OBSERVACAO,SEXO,BAIRRO_CIDADAO,REGIONAL_CIDADAO,DATA_NASC,TIPO_CIDADAO,ORGAO_RESP,RESPOSTA_FINAL
0,6669771,SOLICITAÇÃO,INSTITUTO DAS CIDADES INTELIGENTES,09/11/2016,21:02:44,ABORDAGEM SOCIAL DE RUA - ADULTO,PESSOAS/FAMÍLIAS EM DESABRIGO NA RUA,ABORDAGEM SOCIAL DE RUA - ADULTO - PESSOAS/FAM...,"ANDRE DE BARROS, 0",CENTRO,Unidade Regional Matriz,NENHUM,NÃO SOUBE INFORMAR NUMERAÇÃO PREDIAL,M,NaN,NaN,NaN,CIDADÃO,FUNDAÇÃO DE AÇÃO SOCIAL,Abordagem realizada. Pessoa foi orientada quan...
1,6718351,SOLICITAÇÃO,INSTITUTO DAS CIDADES INTELIGENTES,27/12/2016,00:40:04,ABORDAGEM SOCIAL DE RUA - ADULTO,PERDIDA/DESORIENTADA,ABORDAGEM SOCIAL DE RUA - ADULTO - PERDIDA/DES...,"NILO CAIRO, 0",CENTRO,Unidade Regional Matriz,NENHUM,"NÃO SOUBE INFORMAR NUMERAÇÃO PREDIAL, RELATA E...",M,NaN,NaN,NaN,CIDADÃO,FUNDAÇÃO DE AÇÃO SOCIAL,"EM ABORDAGEM REALIZADA, NÃO FOI ENCONTRADA A P..."
2,6702371,SOLICITAÇÃO,INSTITUTO DAS CIDADES INTELIGENTES,07/12/2016,14:09:42,ABORDAGEM SOCIAL DE RUA - CRIANÇA,ALCOOLIZADAS/DROGADAS,ABORDAGEM SOCIAL DE RUA - CRIANÇA - ALCOOLIZAD...,"VISCONDE DE NACAR, 1210",CENTRO,Unidade Regional Matriz,NENHUM,NaN,F,NaN,NaN,NaN,CIDADÃO,FUNDAÇÃO DE AÇÃO SOCIAL,"- EM ABORDAGEM REALIZADA, NÃO FOI ENCONTRADA A..."
3,6718692,SOLICITAÇÃO,INSTITUTO DAS CIDADES INTELIGENTES,27/12/2016,13:28:27,ABORDAGEM SOCIAL DE RUA - ADULTO,PESSOAS/FAMÍLIAS EM DESABRIGO NA RUA,ABORDAGEM SOCIAL DE RUA - ADULTO - PESSOAS/FAM...,"MARECHAL DEODORO, 0",CENTRO,Unidade Regional Matriz,NENHUM,NaN,M,NaN,NaN,NaN,CIDADÃO,FUNDAÇÃO DE AÇÃO SOCIAL,A pessoa da solicitação já foi abordada nesta ...
4,6704503,SOLICITAÇÃO,INSTITUTO DAS CIDADES INTELIGENTES,09/12/2016,01:28:16,ABORDAGEM SOCIAL DE RUA - ADULTO,DORMINDO/CAÍDAS NA RUA,ABORDAGEM SOCIAL DE RUA - ADULTO - DORMINDO/CA...,"MARECHAL DEODORO, 0",CENTRO,Unidade Regional Matriz,NENHUM,NÃO SOUBE INFORMAR NUMERAÇÃO PREDIAL.,M,NaN,NaN,04/06/1997,CIDADÃO,FUNDAÇÃO DE AÇÃO SOCIAL,A pessoa da solicitação já faz parte da rede d...
5,6672832,SOLICITAÇÃO,INSTITUTO DAS CIDADES INTELIGENTES,12/11/2016,02:29:24,ABORDAGEM SOCIAL DE RUA - ADULTO,DORMINDO/CAÍDAS NA RUA,ABORDAGEM SOCIAL DE RUA - ADULTO - DORMINDO/CA...,"XV DE NOVEMBRO, 0",CENTRO,Unidade Regional Matriz,NENHUM,NÃO INFORMOU NUMERAÇÃO PREDIAL.,M,NaN,NaN,29/12/1971,CIDADÃO,FUNDAÇÃO DE AÇÃO SOCIAL,A pessoa da solicitação já faz parte da rede d...
6,6712943,SOLICITAÇÃO,INSTITUTO DAS CIDADES INTELIGENTES,17/12/2016,16:06:04,TRÂNSITO,VEÍCULO ESTACIONADO - GUIA REBAIXADA,TRÂNSITO - VEÍCULO ESTACIONADO - GUIA REBAIXADA,"CRUZ MACHADO, 396",CENTRO,Unidade Regional Matriz,TELEFONE,NaN,M,NaN,NaN,NaN,CIDADÃO,SECRETARIA MUNICIPAL DE TRÂNSITO,Informamos que o atendimento aos pedidos para ...
7,6733811,INFORMAÇÃO,SECRETARIA MUNICIPAL DA SAÚDE,11/01/2017,12:11:12,CRM-AF/SMS,RECURSOS MATERIAIS - MEDICAMENTOS,CRM-AF/SMS - RECURSOS MATERIAIS - MEDICAMENTOS,"JAIME REIS, 331",SAO FRANCISCO,Unidade Regional Matriz,NENHUM,NaN,F,NaN,NaN,04/08/1957,CIDADÃO,SECRETARIA MUNICIPAL DA SAÚDE,Alendronato de sódio 70 mg e Carbonato de cálc...
8,6710218,INFORMAÇÃO,SECRETARIA MUNICIPAL DA SAÚDE,14/12/2016,10:19:29,CRM-AF/SMS,RECURSOS MATERIAIS - MEDICAMENTOS,CRM-AF/SMS - RECURSOS MATERIAIS - MEDICAMENTOS,"JAIME REIS, 331",SAO FRANCISCO,Unidade Regional Matriz,NENHUM,NaN,F,NaN,NaN,18/08/1938,CIDADÃO,SECRETARIA MUNICIPAL DA SAÚDE,ALENDRONATO DE SÓDIO 70 MG E CARBONATO DE CÁL...
9,6701219,SOLICITAÇÃO,INSTITUTO DAS CIDADES INTELIGENTES,06/12/2016,19:01:01,ABORDAGEM SOCIAL DE RUA - ADULTO,DORMINDO/CAÍDAS NA RUA,ABORDAGEM SOCIAL DE RUA - ADULTO - DORMINDO/CA...,"BARAO DO RIO BRANCO, 720",CENTRO,Unidade Regional Matriz,NENHUM,HOMEM USA CAMISA PRETA CALÇA JEANS E TÊNIS BRA...,M,NaN,NaN,13/02/1980,CIDADÃO,FUNDAÇÃO DE AÇÃO SOCIAL,"EM ABORDAGEM REALIZADA, NÃO FOI ENCONTRADA A P..."

Use o método `info` para exibir as colunas e os tipos identificados.

In [136]:
# Resposta:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7013 entries, 0 to 7012
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   SOLICITACAO       7013 non-null   int64
 1   TIPO              7013 non-null   object
 2   ORGAO             7013 non-null   object
 3   DATA              7013 non-null   object
 4   HORARIO           7013 non-null   object
 5   ASSUNTO           7013 non-null   object
 6   SUBDIVISAO        7013 non-null   object
 7   DESCRICAO         7013 non-null   object
 8   LOGRADOURO_ASS    7013 non-null   object
 9   BAIRRO_ASS        7013 non-null   object
 10  REGIONAL_ASS      7011 non-null   object
 11  MEIO_RESPOSTA     7013 non-null   object
 12  OBSERVACAO        3786 non-null   object
 13  SEXO              7013 non-null   object
 14  BAIRRO_CIDADAO    6897 non-null   object
 15  REGIONAL_CIDADAO  6757 non-null   object
 16  DATA_NASC         6889 non-null   object
 17  TIPO_CIDADAO      7013 non-null   object
 18  ORGAO_RESP        7013 non-null   object
 19  RESPOSTA_FINAL    7010 non-null   object
dtypes: int64(1), object(19)
memory usage: 1.1+ MB

Estamos interessados apenas nos seguintes campos: 'DATA', 'HORARIO', 'ASSUNTO', 'BAIRRO_ASS', 'SEXO', 'DATA_NASC', 'RESPOSTA_FINAL'

Crie (ou substitua) um DataFrame contendo apenas os campos acima.

In [137]:
# Resposta:

df = df.loc[:, ['DATA', 'HORARIO', 'ASSUNTO', 'BAIRRO_ASS','SEXO','DATA_NASC','RESPOSTA_FINAL']].copy()

df = df.copy()

## Localizando e tratando valores inválidos

Exiba todas as linhas com valores em branco (*NaN*).

In [138]:
# Resposta:

df.isnull()

       DATA  HORARIO  ASSUNTO  BAIRRO_ASS   SEXO  DATA_NASC  RESPOSTA_FINAL
0     False    False    False       False  False       True           False
1     False    False    False       False  False       True           False
2     False    False    False       False  False       True           False
3     False    False    False       False  False       True           False
4     False    False    False       False  False      False           False
...     ...      ...      ...         ...    ...        ...             ...
7008  False    False    False       False  False      False           False
7009  False    False    False       False  False      False           False
7010  False    False    False       False  False      False           False
7011  False    False    False       False  False      False           False
7012  False    False    False       False  False      False           False

[7013 rows x 7 columns]

Exclua todas as linhas que contenham algum valor nulo (*NaN*). Verifique se todas as linhas com valores em branco foram excluídas corretamente.

In [139]:
# Resposta:

df = df.dropna()

df

,DATA,HORARIO,ASSUNTO,BAIRRO_ASS,SEXO,DATA_NASC,RESPOSTA_FINAL
4,09/12/2016,01:28:16,ABORDAGEM SOCIAL DE RUA - ADULTO,CENTRO,M,04/06/1997,A pessoa da solicitação já faz parte da rede d...
5,12/11/2016,02:29:24,ABORDAGEM SOCIAL DE RUA - ADULTO,CENTRO,M,29/12/1971,A pessoa da solicitação já faz parte da rede d...
7,11/01/2017,12:11:12,CRM-AF/SMS,SAO FRANCISCO,F,04/08/1957,Alendronato de sódio 70 mg e Carbonato de cálc...
8,14/12/2016,10:19:29,CRM-AF/SMS,SAO FRANCISCO,F,18/08/1938,ALENDRONATO DE SÓDIO 70 MG E CARBONATO DE CÁL...
9,06/12/2016,19:01:01,ABORDAGEM SOCIAL DE RUA - ADULTO,CENTRO,M,13/02/1980,"EM ABORDAGEM REALIZADA, NÃO FOI ENCONTRADA A P..."
...,...,...,...,...,...,...,...
7008,28/11/2016,13:04:25,DRENAGEM,CIDADE INDUSTRIAL,M,14/04/1968,SEM POSSIBILIDADE DE ATENDIMENTO FACE SUSPENSÃ...
7009,22/12/2016,10:11:15,TRÂNSITO,JUVEVE,M,18/05/1989,"Informamos que encaminhamos a viatura 430, às ..."
7010,26/11/2016,21:03:07,ABORDAGEM SOCIAL DE RUA - CRIANÇA,SAO FRANCISCO,F,25/11/1977,"EM ABORDAGEM REALIZADA, NÃO FOI ENCONTRADA A P..."
7011,03/11/2016,15:54:31,NOVO MOBILIÁRIO URBANO,PRADO VELHO,F,15/03/1982,"Prezada cidadã, informamos que a sua solicitaç..."
7012,11/01/2017,20:10:14,ABORDAGEM SOCIAL DE RUA - ADULTO,JARDIM BOTANICO,M,19/10/1987,Em atendimento a solicitação encontrava-se um ...

Faça com que todos os nomes de bairros fiquem em letras minúsculas.

In [140]:
df['BAIRRO_ASS'] = df['BAIRRO_ASS'].str.lower()
df

,DATA,HORARIO,ASSUNTO,BAIRRO_ASS,SEXO,DATA_NASC,RESPOSTA_FINAL
4,09/12/2016,01:28:16,ABORDAGEM SOCIAL DE RUA - ADULTO,centro,M,04/06/1997,A pessoa da solicitação já faz parte da rede d...
5,12/11/2016,02:29:24,ABORDAGEM SOCIAL DE RUA - ADULTO,centro,M,29/12/1971,A pessoa da solicitação já faz parte da rede d...
7,11/01/2017,12:11:12,CRM-AF/SMS,sao francisco,F,04/08/1957,Alendronato de sódio 70 mg e Carbonato de cálc...
8,14/12/2016,10:19:29,CRM-AF/SMS,sao francisco,F,18/08/1938,ALENDRONATO DE SÓDIO 70 MG E CARBONATO DE CÁL...
9,06/12/2016,19:01:01,ABORDAGEM SOCIAL DE RUA - ADULTO,centro,M,13/02/1980,"EM ABORDAGEM REALIZADA, NÃO FOI ENCONTRADA A P..."
...,...,...,...,...,...,...,...
7008,28/11/2016,13:04:25,DRENAGEM,cidade industrial,M,14/04/1968,SEM POSSIBILIDADE DE ATENDIMENTO FACE SUSPENSÃ...
7009,22/12/2016,10:11:15,TRÂNSITO,juveve,M,18/05/1989,"Informamos que encaminhamos a viatura 430, às ..."
7010,26/11/2016,21:03:07,ABORDAGEM SOCIAL DE RUA - CRIANÇA,sao francisco,F,25/11/1977,"EM ABORDAGEM REALIZADA, NÃO FOI ENCONTRADA A P..."
7011,03/11/2016,15:54:31,NOVO MOBILIÁRIO URBANO,prado velho,F,15/03/1982,"Prezada cidadã, informamos que a sua solicitaç..."
7012,11/01/2017,20:10:14,ABORDAGEM SOCIAL DE RUA - ADULTO,jardim botanico,M,19/10/1987,Em atendimento a solicitação encontrava-se um ...

## Conversão de tipos, criação de coluna e escrita em CSV

Exiba os tipos das colunas do DataFrame.

In [141]:
# Resposta:

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6886 entries, 4 to 7012
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   DATA            6886 non-null   object
 1   HORARIO         6886 non-null   object
 2   ASSUNTO         6886 non-null   object
 3   BAIRRO_ASS      6886 non-null   object
 4   SEXO            6886 non-null   object
 5   DATA_NASC       6886 non-null   object
 6   RESPOSTA_FINAL  6886 non-null   object
dtypes: object(7)
memory usage: 430.4+ KB

- Converta os campos de data para o formato DateTime. 
- Crie uma nova coluna chamada HORA, contendo apenas o componete hora do horário da reclamação (dica: use os comandos str.split e str.get)
- Converta a coluna HORA para Inteiro

In [142]:
# Resposta:

df['DATA'] = pd.to_datetime(df['DATA'], format="%d/%m/%Y")
df['DATA_NASC'] = pd.to_datetime(df['DATA_NASC'], format="%d/%m/%Y")

df['HORA'] = df['HORARIO'].str.split(':').str.get(0).astype(int)

Crie uma coluna chamada `IDADE` contendo a diferença entre o ano da reclamação e o ano de nascimento da pessoa.

**Dica:** Para extrair o ano de uma coluna do tipo data, use a propriedade `dt.year`. Por exemplo: `df['DATA'].dt.year`.

In [143]:
# Resposta:

df['IDADE'] = df['DATA'].dt.year - df['DATA_NASC'].dt.year

df

,DATA,HORARIO,ASSUNTO,BAIRRO_ASS,SEXO,DATA_NASC,RESPOSTA_FINAL,HORA,IDADE
4,2016-12-09,01:28:16,ABORDAGEM SOCIAL DE RUA - ADULTO,centro,M,1997-06-04,A pessoa da solicitação já faz parte da rede d...,1,19
5,2016-11-12,02:29:24,ABORDAGEM SOCIAL DE RUA - ADULTO,centro,M,1971-12-29,A pessoa da solicitação já faz parte da rede d...,2,45
7,2017-01-11,12:11:12,CRM-AF/SMS,sao francisco,F,1957-08-04,Alendronato de sódio 70 mg e Carbonato de cálc...,12,60
8,2016-12-14,10:19:29,CRM-AF/SMS,sao francisco,F,1938-08-18,ALENDRONATO DE SÓDIO 70 MG E CARBONATO DE CÁL...,10,78
9,2016-12-06,19:01:01,ABORDAGEM SOCIAL DE RUA - ADULTO,centro,M,1980-02-13,"EM ABORDAGEM REALIZADA, NÃO FOI ENCONTRADA A P...",19,36
...,...,...,...,...,...,...,...,...,...
7008,2016-11-28,13:04:25,DRENAGEM,cidade industrial,M,1968-04-14,SEM POSSIBILIDADE DE ATENDIMENTO FACE SUSPENSÃ...,13,48
7009,2016-12-22,10:11:15,TRÂNSITO,juveve,M,1989-05-18,"Informamos que encaminhamos a viatura 430, às ...",10,27
7010,2016-11-26,21:03:07,ABORDAGEM SOCIAL DE RUA - CRIANÇA,sao francisco,F,1977-11-25,"EM ABORDAGEM REALIZADA, NÃO FOI ENCONTRADA A P...",21,39
7011,2016-11-03,15:54:31,NOVO MOBILIÁRIO URBANO,prado velho,F,1982-03-15,"Prezada cidadã, informamos que a sua solicitaç...",15,34
7012,2017-01-11,20:10:14,ABORDAGEM SOCIAL DE RUA - ADULTO,jardim botanico,M,1987-10-19,Em atendimento a solicitação encontrava-se um ...,20,30

Verifique se as colunas foram corretamente convertidas para os tipos corretos.

In [144]:
# Resposta:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6886 entries, 4 to 7012
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   DATA            6886 non-null   datetime64[ns]
 1   HORARIO         6886 non-null   object
 2   ASSUNTO         6886 non-null   object
 3   BAIRRO_ASS      6886 non-null   object
 4   SEXO            6886 non-null   object
 5   DATA_NASC       6886 non-null   datetime64[ns]
 6   RESPOSTA_FINAL  6886 non-null   object
 7   HORA            6886 non-null   int64
 8   IDADE           6886 non-null   int32
dtypes: datetime64[ns](2), int32(1), int64(1), object(5)
memory usage: 511.1+ KB

Identifique outliers na coluna `IDADE`. Remova do DataFrame todas as reclamações de pessoas com idades muito baixas.

In [145]:
# Resposta:
df['IDADE_zscore'] = (df['IDADE'] - df['IDADE'].mean())/df['IDADE'].std()
df = df[df['IDADE_zscore'] >= -3]

df.sort_values('IDADE_zscore')

,DATA,HORARIO,ASSUNTO,BAIRRO_ASS,SEXO,DATA_NASC,RESPOSTA_FINAL,HORA,IDADE,IDADE_zscore
6268,2016-12-03,21:34:57,"MOTORISTAS, COBRADORES E PORTEIROS",centro,M,2001-06-11,Informamos que encaminhamos o elogio à empresa...,21,15,-2.287881
6838,2016-12-28,19:54:16,ANIMAIS,uberaba,F,2000-05-19,"ENTRADO EM CONTATO COM A CIDADÃ, E ORIENTADA, ...",19,16,-2.218622
6105,2016-11-16,12:00:40,ANIMAIS,cidade industrial,F,2000-01-10,Em caso de animal espancados ou agredido fisi...,12,16,-2.218622
4676,2016-11-11,11:01:27,ANIMAIS DOMÉSTICOS,guabirotuba,F,2000-12-09,Animal recolhido - Ozeas - Rodrigo,11,16,-2.218622
4204,2016-12-16,15:21:47,ÁRVORE,boqueirao,F,2000-02-10,Usuário SIMA: ENCAMINHADO PARA VISTORIA E AVAL...,15,16,-2.218622
...,...,...,...,...,...,...,...,...,...,...
3717,2016-12-07,11:34:56,COLETA,sitio cercado,M,1925-10-12,"O contrato de Coleta de Vegetais, caliças e en...",11,91,2.975805
665,2016-11-29,16:29:40,COLETA,alto da rua xv,F,1925-09-27,"O contrato de Coleta de Vegetais, caliças e en...",16,91,2.975805
1330,2016-11-25,11:09:53,COLETA,capao da imbuia,F,1924-10-02,"O contrato de Coleta de Vegetais, caliças e en...",11,92,3.045064
3004,2016-12-13,09:57:24,COLETA,jardim botanico,M,1923-08-20,"O contrato de Coleta de Vegetais, caliças e en...",9,93,3.114323
5952,2016-11-30,21:34:12,ILUMINAÇÃO PÚBLICA,cidade industrial,M,1920-08-05,SOLICITACAO ATENDIDA,21,96,3.322100

Salve o DataFrame em um arquivo CSV chamado `../data/2017-02-01_156_-_Base_de_Dados_sample-limpo.csv`. Use o parâmetro `index=False` para não incluir o índice no aquivo gerado.

In [146]:
# Resposta:

df.to_csv('../data/2017-02-01_156_-_Base_de_Dados_sample-limpo.csv', index=False)